import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ` flex flex-col`}>
      <div className="text-xl p-2 border">
        <Navbar />
      </div>
        <div className="grow bg-pink-200 overflow-auto">
          {children}
        </div>
      <div className="text-xl p-2 border">Footer</div>
      </body>
    </html>
  );
}
